In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_excel('horse_kick_data.xlsx')
df.head(15)

corps  1875  1876  1877  1878  1879  1880  1881  1882  1883  ...    1886  \
0       G     0     2     2     1     0     0     1     1     0  ...       2   
1       I     0     0     0     2     0     3     0     2     0  ...       1   
2      II     0     0     0     2     0     2     0     0     1  ...       0   
3     III     0     0     0     1     1     1     2     0     2  ...       0   
4      IV     0     1     0     1     1     1     1     0     0  ...       1   
5       V     0     0     0     0     2     1     0     0     1  ...       1   
6      VI     0     0     1     0     2     0     0     1     2  ...       1   
7     VII     1     0     1     0     0     0     1     0     1  ...       0   
8    VIII     1     0     0     0     1     0     0     1     0  ...       0   
9      IX     0     0     0     0     0     2     1     1     1  ...       1   
10      X     0     0     1     1     0     1     0     2     0  ...       0   
11     XI     0     0     0     0     2     4     0     1     3  ...       1   
12    XIV     1     1     2     1     1     3     0     4     0  ...       3   
13     XV     0     1     0     0     0     0     0     1     0  ...       0   
14  total     3     5     7     9    10    18     6    14    11  ...      11   

    1887  1888  1889  1890  1891  1892  1893  1894  total  
0      1     0     0     1     0     1     0     1     16  
1      1     1     0     2     0     3     1     0     16  
2      2     1     1     0     0     2     0     0     12  
3      1     0     1     2     1     0     0     0     12  
4      0     0     0     0     1     1     0     0      8  
5      0     1     1     1     1     1     1     0     11  
6      3     1     1     1     0     3     0     0     17  
7      2     0     0     2     1     0     2     0     12  
8      1     0     0     0     1     1     0     1      7  
9      1     0     1     2     0     1     0     0     13  
10     0     0     2     1     3     0     1     1     15  
11     1     1     2     1     3     1     3     1     25  
12     2     1     0     2     1     1     0     0     24  
13     0     0     2     2     0     0     0     0      8  
14    15     6    11    17    12    15     8     4    196  

[15 rows x 22 columns]

In [3]:
df.drop(columns = ['corps', 'total'], inplace = True)
df.drop(index = 14, inplace = True)
df.head()

1875  1876  1877  1878  1879  1880  1881  1882  1883  1884  1885  1886  \
0     0     2     2     1     0     0     1     1     0     3     0     2   
1     0     0     0     2     0     3     0     2     0     0     0     1   
2     0     0     0     2     0     2     0     0     1     1     0     0   
3     0     0     0     1     1     1     2     0     2     0     0     0   
4     0     1     0     1     1     1     1     0     0     0     0     1   

   1887  1888  1889  1890  1891  1892  1893  1894  
0     1     0     0     1     0     1     0     1  
1     1     1     0     2     0     3     1     0  
2     2     1     1     0     0     2     0     0  
3     1     0     1     2     1     0     0     0  
4     0     0     0     0     1     1     0     0

In [4]:
#X is the database.
X = df.values

#X dimention is 14*20

train_set = X[:, :13]               #Dividing the dataset into training set compraising of first 13 years
test_set = X[:, 13:]                #Dividing the dataset into testing set compraising of last 7 years

print(train_set.shape)
print(test_set.shape)

(14, 13)
(14, 7)


In [5]:
lamda_cap = np.sum(train_set, axis = 1)/float(train_set.shape[1])            #finding lamda_cap using the MLE estimation
lamda_cap.shape = (train_set.shape[0],1)

#Calculating the Root mean sqrare error on the predictions(lamda_cap) for the test set
error = np.sqrt(np.sum((test_set-lamda_cap)**2, axis = 1)/float(test_set.shape[1]))
error.shape = (test_set.shape[0],1)

print('The learnt parametes are as follows:')
print(lamda_cap)
print('The RMSE error of the prediction for each corps are as follows:')
print(error)

The learnt parametes are as follows:
[[1.        ]
 [0.69230769]
 [0.61538462]
 [0.61538462]
 [0.46153846]
 [0.38461538]
 [0.84615385]
 [0.53846154]
 [0.30769231]
 [0.69230769]
 [0.53846154]
 [1.        ]
 [1.46153846]
 [0.30769231]]
The RMSE error of the prediction for each corps are as follows:
[[0.75592895]
 [1.11244402]
 [0.72975638]
 [0.72975638]
 [0.48476363]
 [0.58798911]
 [0.98980432]
 [0.89801133]
 [0.50942097]
 [0.73839285]
 [1.15969215]
 [1.13389342]
 [1.02380789]
 [0.94121376]]


In [6]:
print(train_set)

[[0 2 2 1 0 0 1 1 0 3 0 2 1]
 [0 0 0 2 0 3 0 2 0 0 0 1 1]
 [0 0 0 2 0 2 0 0 1 1 0 0 2]
 [0 0 0 1 1 1 2 0 2 0 0 0 1]
 [0 1 0 1 1 1 1 0 0 0 0 1 0]
 [0 0 0 0 2 1 0 0 1 0 0 1 0]
 [0 0 1 0 2 0 0 1 2 0 1 1 3]
 [1 0 1 0 0 0 1 0 1 1 0 0 2]
 [1 0 0 0 1 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 2 1 1 1 0 2 1 1]
 [0 0 1 1 0 1 0 2 0 2 0 0 0]
 [0 0 0 0 2 4 0 1 3 0 1 1 1]
 [1 1 2 1 1 3 0 4 0 1 0 3 2]
 [0 1 0 0 0 0 0 1 0 1 1 0 0]]


In [7]:
print(test_set)

[[0 0 1 0 1 0 1]
 [1 0 2 0 3 1 0]
 [1 1 0 0 2 0 0]
 [0 1 2 1 0 0 0]
 [0 0 0 1 1 0 0]
 [1 1 1 1 1 1 0]
 [1 1 1 0 3 0 0]
 [0 0 2 1 0 2 0]
 [0 0 0 1 1 0 1]
 [0 1 2 0 1 0 0]
 [0 2 1 3 0 1 1]
 [1 2 1 3 1 3 1]
 [1 0 2 1 1 0 0]
 [0 2 2 0 0 0 0]]
